spring:
  application:
    name: provider-mail
  mail:
    host: smtp.qq.com
    # 你的邮箱授权码
    password: kbebpqxwxdfydhij
    username: 2375622526@qq.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    # 发送邮件的邮箱地址
  jackson:
    default-property-inclusion: non_null
  redis:
    database: 0
    host: 47.107.140.147
    port: 6379
    password: 2375622526
    timeout: 200
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-wait: -1
        max-active: 8
  thymeleaf:
    cache: false # 开发时关闭缓存,不然没法看到实时页面
    mode: HTML # 用非严格的 HTML
    encoding: UTF-8
    servlet:
      content-type: text/html


server:
  port: 82
business:
  host: localhost:81
logging:
  path: logs/
